@host=https://localhost:7142
GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjODA1NWViNS1hZGNjLTQ4ZjctYTc3Zi0wMzU4ZTA4YzQxNjciLCJnaXZlbl9uYW1lIjoiT3Vzc2FtYSIsImZhbWlseV9uYW1lIjoiWmFyaWYiLCJqdGkiOiJiNGE5MWFkNC1hOGI1LTQ1MmItYWJkYy01ZTFhMDE4OThlNTMiLCJleHAiOjE2Njc3NjYyMDgsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.VCnlUdXG7_aYtc-j-zcmGfvBGQUCpDpJUsxpEuUxvdU



